export const tasArchiveData = {
    title: "Prince of Persia Tool-Assisted Speedruns",
    description: "A comprehensive community archive of Tool-Assisted Speedruns (TAS) across the Prince of Persia franchise, featuring video encodes, commentary tracks, and author notes links.",
    totalRuns: 45,
    runs: [
    {
        "id": 1,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "NES",
        "platformRaw": "NES",
        "region": null,
        "category": "Any%",
        "tasers": "Mclaud2000",
        "date": "27-Mar-2004",
        "tasTime": "0:19:16.70",
        "rtaIgt": "0:19:00",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/174S",
        "videoUrl": "https://www.youtube.com/watch?v=5kvsptkHzeY",
        "commentaryUrl": null
    },
    {
        "id": 2,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "Genesis",
        "platformRaw": "Genesis",
        "region": "USA",
        "category": "Any%",
        "tasers": "SprintGod",
        "date": "26-Aug-2004",
        "tasTime": "0:19:45.35",
        "rtaIgt": "0:19:44",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/289S",
        "videoUrl": "https://www.youtube.com/watch?v=Vm55FeK5Upo",
        "commentaryUrl": null
    },
    {
        "id": 3,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "NES",
        "platformRaw": "NES",
        "region": null,
        "category": "Any%",
        "tasers": "SprintGod",
        "date": "28-Aug-2004",
        "tasTime": "0:16:39.05",
        "rtaIgt": "0:16:26",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/282S",
        "videoUrl": "https://www.youtube.com/watch?v=ynxzTTVhbTI",
        "commentaryUrl": null
    },
    {
        "id": 4,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any%",
        "tasers": "nitsuja",
        "date": "06-May-2005",
        "tasTime": "0:11:00.42",
        "rtaIgt": "0:10:32",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/569S",
        "videoUrl": "https://www.youtube.com/watch?v=5WKIY_CwJMg",
        "commentaryUrl": null
    },
    {
        "id": 5,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any%",
        "tasers": "fuzi2",
        "date": "08-Sep-2005",
        "tasTime": "0:34:41.38",
        "rtaIgt": "0:34:35",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/779S",
        "videoUrl": "https://www.youtube.com/watch?v=MnctX3VNTFw",
        "commentaryUrl": null
    },
    {
        "id": 6,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any% (No Warp)",
        "tasers": "SprintGod",
        "date": "05-Nov-2005",
        "tasTime": "0:34:01.65",
        "rtaIgt": "0:33:55",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/817S",
        "videoUrl": "https://www.youtube.com/watch?v=KTRDX6YGGyw",
        "commentaryUrl": null
    },
    {
        "id": 7,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "NES",
        "platformRaw": "NES",
        "region": null,
        "category": "Any%",
        "tasers": "SprintGod",
        "date": "16-Mar-2006",
        "tasTime": "0:16:27.82",
        "rtaIgt": "0:16:13",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/1002S",
        "videoUrl": "https://www.youtube.com/watch?v=RP-DlT_bzsk",
        "commentaryUrl": null
    },
    {
        "id": 8,
        "game": "Prince of Persia: The Sands of Time",
        "year": "2003",
        "gameSlug": "pop_sot",
        "platform": "GBA",
        "platformRaw": "GBA",
        "region": null,
        "category": "Any%",
        "tasers": "theenglishman",
        "date": "22-Jan-2008",
        "tasTime": "0:42:15.00",
        "rtaIgt": "0:42:24",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/1805S",
        "videoUrl": "https://www.youtube.com/watch?v=AYH4JlHCe2Q",
        "commentaryUrl": null
    },
    {
        "id": 9,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "Genesis",
        "platformRaw": "Genesis",
        "region": "USA",
        "category": "Any%",
        "tasers": "aqfaq",
        "date": "18-Sep-2008",
        "tasTime": "0:19:03.48",
        "rtaIgt": "0:19:03",
        "isFastest": true,
        "notesUrl": "https://tasvideos.org/2084S",
        "videoUrl": "https://www.youtube.com/watch?v=9b2_93RQWjI",
        "commentaryUrl": null
    },
    {
        "id": 10,
        "game": "Prince of Persia: The Sands of Time",
        "year": "2003",
        "gameSlug": "pop_sot",
        "platform": "GBA",
        "platformRaw": "GBA",
        "region": null,
        "category": "Any%",
        "tasers": "theenglishman",
        "date": "03-Nov-2008",
        "tasTime": "0:36:17.73",
        "rtaIgt": "0:36:24",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/2123S",
        "videoUrl": "https://www.youtube.com/watch?v=6G6gphz6Pq0",
        "commentaryUrl": null
    },
    {
        "id": 11,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "GBC",
        "platformRaw": "GBC",
        "region": null,
        "category": "Any%",
        "tasers": "TimmyAkmed, NintendoHardGamer",
        "date": "12-May-2014",
        "tasTime": null,
        "rtaIgt": "0:04:11",
        "isFastest": false,
        "notesUrl": null,
        "videoUrl": "https://www.youtube.com/watch?v=yAxdhthSrgg",
        "commentaryUrl": null
    },
    {
        "id": 12,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any%",
        "tasers": "Alyosha",
        "date": "03-Sep-2015",
        "tasTime": "0:11:11.94",
        "rtaIgt": "0:10:44",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/4815S",
        "videoUrl": "https://www.youtube.com/watch?v=LdkEMr1cMn4",
        "commentaryUrl": null
    },
    {
        "id": 13,
        "game": "Prince of Persia: The Sands of Time",
        "year": "2003",
        "gameSlug": "pop_sot",
        "platform": "GBA",
        "platformRaw": "GBA",
        "region": null,
        "category": "100%",
        "tasers": "theenglishman",
        "date": "11-Dec-2016",
        "tasTime": "1:14:16.72",
        "rtaIgt": "1:14:06",
        "isFastest": true,
        "notesUrl": "https://tasvideos.org/5212S",
        "videoUrl": "https://www.youtube.com/watch?v=kPpEglJStmM",
        "commentaryUrl": "https://www.youtube.com/watch?v=Jxve5s__By8"
    },
    {
        "id": 14,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any% (No Warp)",
        "tasers": "Challenger, Odongdong",
        "date": "01-Dec-2016",
        "tasTime": "0:33:31.20",
        "rtaIgt": "0:33:23",
        "isFastest": false,
        "notesUrl": "https://toolassisted.run/runs/M3271",
        "videoUrl": "https://www.youtube.com/watch?v=MOmrwNRn5mY",
        "commentaryUrl": null
    },
    {
        "id": 15,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any%",
        "tasers": "Challenger",
        "date": "11-Dec-2016",
        "tasTime": "0:09:18.85",
        "rtaIgt": "0:08:50",
        "isFastest": false,
        "notesUrl": "https://toolassisted.run/runs/M3277",
        "videoUrl": "https://www.youtube.com/watch?v=m3e66d7DsqI",
        "commentaryUrl": null
    },
    {
        "id": 16,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SegaCD",
        "platformRaw": "SegaCD",
        "region": null,
        "category": "Any%",
        "tasers": "Challenger",
        "date": "28-Jan-2017",
        "tasTime": "0:19:09.80",
        "rtaIgt": "0:18:49",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M3317",
        "videoUrl": "https://www.youtube.com/watch?v=ePmgf760XRE",
        "commentaryUrl": null
    },
    {
        "id": 17,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "TG-16",
        "platformRaw": "TG-16",
        "region": null,
        "category": "Any%",
        "tasers": "Challenger",
        "date": "23-Sep-2017",
        "tasTime": "0:05:14.31",
        "rtaIgt": "0:05:09",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M3523",
        "videoUrl": "https://www.youtube.com/watch?v=TP7KhaSHats",
        "commentaryUrl": null
    },
    {
        "id": 18,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Training Mode",
        "tasers": "Challenger",
        "date": "10-Apr-2018",
        "tasTime": "0:03:31.10",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M3670",
        "videoUrl": "https://www.youtube.com/watch?v=b5udoaxymGI",
        "commentaryUrl": null
    },
    {
        "id": 19,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any%",
        "tasers": "NhatNM",
        "date": "25-Jul-2018",
        "tasTime": "0:31:31.48",
        "rtaIgt": "0:31:06",
        "isFastest": true,
        "notesUrl": "https://tasvideos.org/6057S",
        "videoUrl": "https://www.youtube.com/watch?v=KDiuQ1M8r04",
        "commentaryUrl": null
    },
    {
        "id": 20,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "NES",
        "platformRaw": "NES",
        "region": null,
        "category": "Any%",
        "tasers": "Challenger",
        "date": "10-Apr-2020",
        "tasTime": "0:16:16.06",
        "rtaIgt": "0:16:03",
        "isFastest": false,
        "notesUrl": "https://toolassisted.run/runs/M4158",
        "videoUrl": "https://www.youtube.com/watch?v=SBYANuJZT6o",
        "commentaryUrl": null
    },
    {
        "id": 21,
        "game": "Prince of Persia: The Two Thrones",
        "year": "2005",
        "gameSlug": "pop_t2t",
        "platform": "GCN",
        "platformRaw": "GCN",
        "region": null,
        "category": "Any% (NMG)",
        "tasers": "Vynneve",
        "date": "13-May-2020",
        "tasTime": "1:43:46.77",
        "rtaIgt": "1:31:24",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/6550S",
        "videoUrl": "https://www.youtube.com/watch?v=H2Ufmg3bbjo",
        "commentaryUrl": "https://www.youtube.com/watch?v=Qzj5uieiUgw"
    },
    {
        "id": 22,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any% (NMG)",
        "tasers": "GMP",
        "date": "12-Apr-2021",
        "tasTime": null,
        "rtaIgt": "0:17:40",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M100016",
        "videoUrl": "https://www.youtube.com/watch?v=qEUwTODtHLk",
        "commentaryUrl": null
    },
    {
        "id": 23,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "eien86",
        "date": "05-May-2021",
        "tasTime": "0:12:59.65",
        "rtaIgt": "0:12:09",
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/7116S",
        "videoUrl": "https://www.youtube.com/watch?v=hfOocUkxJ08",
        "commentaryUrl": null
    },
    {
        "id": 24,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "eien86",
        "date": "28-Jun-2021",
        "tasTime": "0:13:08.53",
        "rtaIgt": "0:12:10",
        "isFastest": false,
        "notesUrl": "https://toolassisted.run/runs/M4477",
        "videoUrl": "https://www.youtube.com/watch?v=hlScbQsZ46w",
        "commentaryUrl": "https://www.youtube.com/watch?v=dJOOWGUsRYI"
    },
    {
        "id": 25,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "GMP",
        "date": "03-Aug-2021",
        "tasTime": "0:14:50.62",
        "rtaIgt": null,
        "isFastest": false,
        "notesUrl": "https://tasvideos.org/7180S",
        "videoUrl": "https://www.youtube.com/watch?v=WU8xglub3To",
        "commentaryUrl": null
    },
    {
        "id": 26,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "Genesis",
        "platformRaw": "Genesis",
        "region": null,
        "category": "Any%",
        "tasers": "eien86",
        "date": "09-Aug-2021",
        "tasTime": "0:19:38.18",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M4535",
        "videoUrl": "https://www.youtube.com/watch?v=hmQz6MVNyfw",
        "commentaryUrl": null
    },
    {
        "id": 27,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "eien86, GMP, Challenger",
        "date": "16-Aug-2021",
        "tasTime": "0:14:26.65",
        "rtaIgt": null,
        "isFastest": false,
        "notesUrl": "https://toolassisted.run/runs/M4531",
        "videoUrl": "https://www.youtube.com/watch?v=5ihYRMHbU5U",
        "commentaryUrl": "https://www.youtube.com/watch?v=bt4nFGf0Wxs"
    },
    {
        "id": 28,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "GMP",
        "date": "26-Oct-2021",
        "tasTime": "0:14:11.00",
        "rtaIgt": null,
        "isFastest": false,
        "notesUrl": "https://toolassisted.run/runs/M100004",
        "videoUrl": "https://www.youtube.com/watch?v=Ouh3Jc2B4qU",
        "commentaryUrl": "https://www.youtube.com/watch?v=SMI2d9-YqnI"
    },
    {
        "id": 29,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "GMP",
        "date": "26-Oct-2021",
        "tasTime": "0:14:47.45",
        "rtaIgt": "0:13:32",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M4638",
        "videoUrl": "https://www.youtube.com/watch?v=bVoebAC-6GQ",
        "commentaryUrl": "https://www.youtube.com/watch?v=Ikz2azVfqyc"
    },
    {
        "id": 30,
        "game": "Prince of Persia 2",
        "year": "1993",
        "gameSlug": "pop2",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any%",
        "tasers": "Challenger",
        "date": "03-Dec-2021",
        "tasTime": "0:07:59.84",
        "rtaIgt": "0:07:31",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M4565",
        "videoUrl": "https://www.youtube.com/watch?v=epkmBlaDyHY",
        "commentaryUrl": null
    },
    {
        "id": 31,
        "game": "Prince of Persia: The Fallen King",
        "year": "2008",
        "gameSlug": "pop_tfk",
        "platform": "DS",
        "platformRaw": "NDS",
        "region": null,
        "category": "Any%",
        "tasers": "GMP",
        "date": "29-Dec-2021",
        "tasTime": "2:23:31.68",
        "rtaIgt": "2:22:41",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M4591",
        "videoUrl": "https://www.youtube.com/watch?v=OoPWX30wsGA",
        "commentaryUrl": "https://www.youtube.com/watch?v=MeJ-Le27JuM"
    },
    {
        "id": 32,
        "game": "Prince of Persia: The Sands of Time",
        "year": "2003",
        "gameSlug": "pop_sot",
        "platform": "GBA",
        "platformRaw": "GBA",
        "region": null,
        "category": "Any%",
        "tasers": "GMP",
        "date": "14-Mar-2022",
        "tasTime": "0:28:37.38",
        "rtaIgt": "0:28:26",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M4618",
        "videoUrl": "https://www.youtube.com/watch?v=vrlG0V6Migg",
        "commentaryUrl": "https://www.youtube.com/watch?v=df-jXeRRQ1w"
    },
    {
        "id": 33,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "NES",
        "platformRaw": "NES",
        "region": null,
        "category": "Any%",
        "tasers": "eien86",
        "date": "02-Apr-2022",
        "tasTime": "0:15:20.05",
        "rtaIgt": "0:12:13",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M4651",
        "videoUrl": "https://www.youtube.com/watch?v=dU3hOh2Rb8g",
        "commentaryUrl": null
    },
    {
        "id": 34,
        "game": "Prince of Persia: Warrior Within",
        "year": "2004",
        "gameSlug": "pop_ww",
        "platform": "GCN",
        "platformRaw": "GCN",
        "region": null,
        "category": "Any % (Zipless)",
        "tasers": "GMP",
        "date": "13-Dec-2022",
        "tasTime": "0:24:56.15",
        "rtaIgt": "0:16:50",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5029",
        "videoUrl": "https://www.youtube.com/watch?v=HyYQD3EYAPk",
        "commentaryUrl": null
    },
    {
        "id": 35,
        "game": "Prince of Persia: Warrior Within",
        "year": "2004",
        "gameSlug": "pop_ww",
        "platform": "GCN",
        "platformRaw": "GCN",
        "region": null,
        "category": "True Ending (NMG)",
        "tasers": "Pankaj",
        "date": "19-Dec-2022",
        "tasTime": "1:56:51.47",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5063",
        "videoUrl": "https://www.youtube.com/watch?v=o7ebf1xs564",
        "commentaryUrl": null
    },
    {
        "id": 36,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "Any%",
        "tasers": "eien86",
        "date": "24-Feb-2023",
        "tasTime": "0:13:59.15",
        "rtaIgt": "0:11:59",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5206",
        "videoUrl": "https://www.youtube.com/watch?v=a9cFrIkpg58",
        "commentaryUrl": null
    },
    {
        "id": 37,
        "game": "Prince of Persia: The Two Thrones",
        "year": "2005",
        "gameSlug": "pop_t2t",
        "platform": "GCN",
        "platformRaw": "GCN",
        "region": null,
        "category": "Any% (NMG)",
        "tasers": "Pankaj",
        "date": "15-Apr-2023",
        "tasTime": "1:39:11.65",
        "rtaIgt": "1:26:56",
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5300",
        "videoUrl": "https://www.youtube.com/watch?v=wwdWlLrS8sM",
        "commentaryUrl": null
    },
    {
        "id": 38,
        "game": "Prince of Persia: The Sands of Time",
        "year": "2003",
        "gameSlug": "pop_sot",
        "platform": "GCN",
        "platformRaw": "GCN",
        "region": null,
        "category": "Any% (NMG)",
        "tasers": "GMP",
        "date": "24-Feb-2023",
        "tasTime": "1:21:05.15",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5358",
        "videoUrl": "https://www.youtube.com/watch?v=tijiavSRDjI",
        "commentaryUrl": "https://youtube.com/watch?v=dS-zpj31Ers"
    },
    {
        "id": 39,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "SNES",
        "platformRaw": "SNES",
        "region": null,
        "category": "Any% (No Warp)",
        "tasers": "Challenger & eien86",
        "date": "12-Dec-2023",
        "tasTime": "0:32:33.90",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5744",
        "videoUrl": "https://www.youtube.com/watch?v=UoMci7r0E40",
        "commentaryUrl": null
    },
    {
        "id": 40,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "DOS",
        "platformRaw": "DOS",
        "region": null,
        "category": "100%",
        "tasers": "eien86",
        "date": "01-Jan-2024",
        "tasTime": "0:27:18.76",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M5799",
        "videoUrl": "https://www.youtube.com/watch?v=LjzxE7icN8c",
        "commentaryUrl": null
    },
    {
        "id": 41,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "Amiga",
        "platformRaw": "Amiga",
        "region": null,
        "category": "Any%",
        "tasers": "eien86",
        "date": "11-Jan-2025",
        "tasTime": "0:18:36.62",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M6417",
        "videoUrl": "https://www.youtube.com/watch?v=O_8Rsz5BaCQ",
        "commentaryUrl": null
    },
    {
        "id": 42,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "GBC",
        "platformRaw": "GBC",
        "region": null,
        "category": "Any%",
        "tasers": "eien86, TimmyAkmed & NintendoHardGamer",
        "date": "19-Jan-2025",
        "tasTime": "0:04:18.97",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M6387",
        "videoUrl": "https://www.youtube.com/watch?v=oA2IdxjVgtA",
        "commentaryUrl": null
    },
    {
        "id": 43,
        "game": "Prince of Persia: Special Edition",
        "year": "2003",
        "gameSlug": "pop_special_edition",
        "platform": "Flash",
        "platformRaw": "Flash",
        "region": null,
        "category": "Any%",
        "tasers": "Rxser",
        "date": "24-Jan-2025",
        "tasTime": "0:02:02.72",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M6373",
        "videoUrl": "https://www.youtube.com/watch?v=ChOYKUHTP5c",
        "commentaryUrl": null
    },
    {
        "id": 44,
        "game": "Prince of Persia",
        "year": "1989",
        "gameSlug": "pop1",
        "platform": "Genesis",
        "platformRaw": "Genesis",
        "region": "Europe",
        "category": "Any%",
        "tasers": "eien86",
        "date": "09-Feb-2025",
        "tasTime": "0:22:40.26",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M6396",
        "videoUrl": "https://www.youtube.com/watch?v=1UXjysIMa3k",
        "commentaryUrl": null
    },
    {
        "id": 45,
        "game": "Prince of Persia: The Sands of Time",
        "year": "2003",
        "gameSlug": "pop_sot",
        "platform": "GCN",
        "platformRaw": "GCN",
        "region": null,
        "category": "Any% (Zipless)",
        "tasers": "GMP",
        "date": "08-Jan-2026",
        "tasTime": "0:57:37.32",
        "rtaIgt": null,
        "isFastest": true,
        "notesUrl": "https://toolassisted.run/runs/M6986",
        "videoUrl": "https://www.youtube.com/watch?v=t6rP0vbR33k",
        "commentaryUrl": "https://youtube.com/watch?v=klUmBuYTLmE"
    }
],
    bonusRuns: [
    {
        "title": "Sands of Time GCN - Zipless Partial TAS",
        "author": "Solarplex",
        "links": [
            {
                "label": "UserFile",
                "url": "https://tasvideos.org/userfiles/info/17844006491402377"
            },
            {
                "label": "YouTube Video",
                "url": "https://www.youtube.com/watch?v=4vdPN3ZE3Jo"
            }
        ],
        "description": "Incomplete zipless TAS due to technical issues. First TAS of the game."
    },
    {
        "title": "PoP1 DOS Level Skip TAS",
        "author": "DavidXNewton",
        "links": [
            {
                "label": "YouTube Video",
                "url": "https://www.youtube.com/watch?v=vIjM2Sy7pOo"
            }
        ],
        "description": "First TAS of the DOS version of PoP."
    },
    {
        "title": "PoP1 TurboGrafx-16 (Alternative Run)",
        "author": "Nintendo 128",
        "links": [
            {
                "label": "YouTube Video",
                "url": "https://www.youtube.com/watch?v=xgYeG8qwNCA"
            }
        ],
        "description": "Alternative TG-16 route demonstration."
    },
    {
        "title": "PoP: The Sands of Time - First Split",
        "author": "Vynneve",
        "links": [
            {
                "label": "YouTube Video",
                "url": "https://www.youtube.com/watch?v=fOFJB9N8yFs"
            }
        ],
        "description": "Dagger segment with first person glitches."
    },
    {
        "title": "PoP: Warrior Within - First Split",
        "author": "Vynneve",
        "links": [
            {
                "label": "YouTube Video",
                "url": "https://www.youtube.com/watch?v=2qar3m394KQ"
            }
        ],
        "description": "Boat Segment, first TAS of this game."
    },
    {
        "title": "PoP: The Two Thrones - First Split",
        "author": "GMP",
        "links": [
            {
                "label": "YouTube Video",
                "url": "https://www.youtube.com/watch?v=bwA54ios5sA"
            }
        ],
        "description": "Ramparts segment with optimised strats."
    },
]
};

export default tasArchiveData;
