const loadTriggers = [
    { "name": "AI Break", "coords": [-353, -358, -24] },
    { "name": "Collapsed Bridge", "coords": [-301, -187, -28] },
    { "name": "Barrier Skip", "coords": [-243, -163, -28] },
    { "name": "Canyon - Desert", "coords": [-172, -142, -37] },
    { "name": "Inner Door", "coords": [7, -357, -29] },
    { "name": "Mid-Corridor", "coords": [7, -310, -32] },
    { "name": "Outer Door", "coords": [7, -260, -32] },
    { "name": "Outer Temple", "coords": [6, -174, -49] },
    { "name": "Temple - Desert Left Junction", "coords": [-210, 4, -43] },
    { "name": "Desert Left Junction - Temple", "coords": [-258, 10, -27] },
    { "name": "Temple - Desert Middle Junction", "coords": [-4, 78, -42] },
    { "name": "Desert Middle Junction - Temple", "coords": [0, 107, -18] },
    { "name": "Temple - Desert Right Junction", "coords": [221, -2, -46] },
    { "name": "Desert Right Junction - Temple", "coords": [258, 6, -18] },
    { "name": "Desert Left Junction - King's Gate", "coords": [-330, -1, -10] },
    { "name": "King's Gate - Desert Left Junction", "coords": [-362, -57, 11] },
    { "name": "King's Gate - Sun Temple", "coords": [-468, -86, 25] },
    { "name": "Sun Temple - King's Gate", "coords": [-549, -52, 10] },
    { "name": "Sun Temple - Martyrs' Tower", "coords": [-561, 34, 11] },
    { "name": "Martyrs' Tower - Sun Temple", "coords": [-545, 115, 12] },
    { "name": "Sun Temple - Marshalling Grounds", "coords": [-663, -56, 11] },
    { "name": "Marshalling Grounds - Sun Temple", "coords": [-731, -64, 10] },
    { "name": "Marshalling Grounds - Windmills", "coords": [-807, 20, 16] },
    { "name": "Windmills - Marshalling Grounds", "coords": [-806, 104, 18] },
    { "name": "Windmills - Hunter's Lair", "coords": [-808, 210, 30] },
    { "name": "Hunter's Lair - Windmills", "coords": [-907, 259, -11] },
    { "name": "Windmills - Martyrs' Tower", "coords": [-713, 205, 22] },
    { "name": "Martyrs' Tower - Windmills", "coords": [-630, 203, 22] },
    { "name": "Martyrs' Tower - Machinery Ground", "coords": [-528, 237, 25] },
    { "name": "Machinery Ground - Martyrs' Tower", "coords": [-468, 396, 26] },
    { "name": "Machinery Ground - Martyrs' Tower", "coords": [-506, 336, 26] },
    { "name": "Desert Left Junction - Cauldron", "coords": [-260, 75, -20] },
    { "name": "Cauldron - Desert Left Junction", "coords": [-205, 131, -5] },
    { "name": "Desert Middle Junction - Cauldron", "coords": [-18, 154, -13] },
    { "name": "Cauldron - Desert Middle Junction", "coords": [-101, 164, -11] },
    { "name": "Cauldron - Construction Yard", "coords": [-137, 243, -8] },
    { "name": "Construction Yard - Cauldron", "coords": [-182, 308, 30] },
    { "name": "Construction Yard - Reservoir", "coords": [-141, 421, 36] },
    { "name": "Reservoir - Construction Yard", "coords": [-134, 524, 43] },
    { "name": "Construction Yard - Machinery Ground", "coords": [-279, 326, 19] },
    { "name": "Machinery Ground - Construction Yard", "coords": [-346, 381, 19] },
    { "name": "Machinery Ground - Heaven's Stair", "coords": [-363, 478, 15] },
    { "name": "Heaven's Stair - Machinery Ground", "coords": [-335, 537, 14] },
    { "name": "Heaven's Stair - Observatory", "coords": [-266, 619, 146] },
    { "name": "Observatory - Heaven's Stair", "coords": [-311, 634, 220] },
    { "name": "Heaven's Stair - Reservoir", "coords": [-246, 632, 20] },
    { "name": "Reservoir - Heaven's Stair", "coords": [-139, 633, 27] },
    { "name": "Reservoir - Spire of Dreams", "coords": [-59, 532, 41] },
    { "name": "Reservoir - Spire of Dreams", "coords": [36, 536, 60] },
    { "name": "Spire of Dreams - Reservoir", "coords": [128, 534, 47] },
    { "name": "Desert Middle Junction - Cavern", "coords": [45, 159, -17] },
    { "name": "Cavern - Desert Middle Junction", "coords": [85, 185, -9] },
    { "name": "Desert Right Junction - Cavern", "coords": [244, 77, -13] },
    { "name": "Cavern - Desert Right Junction", "coords": [214, 158, -13] },
    { "name": "Cavern - Royal Gardens", "coords": [164, 252, 2] },
    { "name": "Royal Gardens - Cavern", "coords": [238, 306, 28] },
    { "name": "Royal Gardens - Royal Spire", "coords": [321, 377, 28] },
    { "name": "Royal Spire - Royal Gardens", "coords": [399, 393, 32] },
    { "name": "Royal Gardens - Spire of Dreams", "coords": [208, 390, 28] },
    { "name": "Spire of Dreams - Royal Gardens", "coords": [181, 475, 27] },
    { "name": "Spire of Dreams - Coronation Hall", "coords": [211, 571, 35] },
    { "name": "Coronation Hall - Spire of Dreams", "coords": [296, 614, 34] },
    { "name": "Coronation Hall - Palace Rooms", "coords": [349, 668, 36] },
    { "name": "Palace Rooms - Coronation Hall", "coords": [339, 723, 42] },
    { "name": "Coronation Hall - Royal Spire", "coords": [390, 550, 35] },
    { "name": "Royal Spire - Coronation Hall", "coords": [433, 474, 35] },
    { "name": "Royal Spire - Tower of Ormazd", "coords": [484, 421, 34] },
    { "name": "Royal Spire - Tower of Ormazd", "coords": [541, 379, 11] },
    { "name": "Tower of Ormazd - Royal Spire", "coords": [640, 303, -22] },
    { "name": "Tower of Ormazd - Royal Spire", "coords": [644, 246, -30] },
    { "name": "Desert Right Junction - City Gate", "coords": [370, 4, -17] },
    { "name": "City Gate - Desert Right Junction", "coords": [307, 28, 0] },
    { "name": "City Gate - Tower of Ahriman", "coords": [480, -30, -18] },
    { "name": "Tower of Ahriman - City Gate", "coords": [550, 0, -34] },
    { "name": "Tower of Ahriman - Queen's Tower", "coords": [640, 17, -31] },
    { "name": "Queen's Tower - Tower of Ahriman", "coords": [750, -36, -36] },
    { "name": "Tower of Ahriman - Tower of Ormazd", "coords": [607, 58, -36] },
    { "name": "Tower of Ormazd - Tower of Ahriman", "coords": [637, 154, -30] },
    { "name": "Tower of Ormazd - City of Light", "coords": [709, 186, -38] },
    { "name": "City of Light - Tower of Ormazd", "coords": [788, 168, -37] },
    { "name": "City of Light - Warrior's Fortress", "coords": [930, 179, -9] },
    { "name": "Warrior's Fortress - City of Light", "coords": [987, 271, -5] },
    { "name": "City of Light - Queen's Tower", "coords": [863, 61, -32] },
    { "name": "Queen's Tower - City of Light", "coords": [866, -4, -33] },
    { "name": "Red Plate", "coords": [-58, -465, -179] },
    { "name": "Blue Plate", "coords": [45, -471, -179] },
    { "name": "Yellow Plate", "coords": [-131, -503, -179] },
    { "name": "Green Plate", "coords": [148, -468, -140] },
    { "name": "Last Realm", "coords": [6, -604, -186] },
    { "name": "Last Realm", "coords": [2, -658, -195] }
]

export default loadTriggers;
